project:
  type: website
  output-dir: docs
  render: 
    - README.md
    - notebooks/terminal_help.qmd

website:
  title: "Folio Landing"
  site-url: "https://amsandler.github.io/folio/"
  navbar:
    background: primary
    left:
      - href: notebooks/terminal_help.qmd
        text: Terminal Help

format:
  html:
    theme: cosmo
    toc: true

